//! H3 #20 criterion X2, execution side: one nonempty assignment acknowledgement certified by two
//! distinct valid signer subsets of the old root quorum is applied by this kernel to identical
//! state.
//!
//! `testdata/h3-assignment-signer-subsets.json` and `testdata/h3-assignment-genesis.json` are
//! copied verbatim from bft-core `engineapi/testdata/` (generated by
//! `TestX2NonemptyAssignmentTransitionIsSignerSubsetIndependent` in `engineapi/
//! h3_signer_subset_test.go`). The root input, transition body and commitment are what bft-core's
//! builder, follower and replay paths handed the execution client for each subset; the witnesses
//! are the only subset-dependent bytes. The genesis is the registry-bearing genesis of the Go
//! deployment whose block 0 is the acknowledgement's frozen parent, so the Go bytes apply here
//! unmodified.

mod support;

use alloy_genesis::Genesis;
use alloy_primitives::{keccak256, Address, B256, U256};
use reth_chainspec::ChainSpec;
use reth_evm::NextBlockEnvAttributes;
use reth_evm_ethereum::EthEvmConfig;
use reth_primitives_traits::SealedHeader;
use reth_unicity_execution::{
    block::BlockProfile,
    block_executor::{build_complete, replay_complete, BoundExecutionInput, UnicityEvmConfig},
    derive_beacon_root, derive_prev_randao, derive_timestamp,
    wire::{SealBuildInput, SealCompanion},
    RootInputV2, SEAL_REGISTRY,
};
use revm::database::State;
use std::{collections::BTreeMap, sync::Arc};
use support::provider::FixtureProvider;

const VECTOR: &str = include_str!("../testdata/h3-assignment-signer-subsets.json");
const GENESIS: &str = include_str!("../testdata/h3-assignment-genesis.json");
const FEE_COLLECTOR: Address = Address::new([0x77; 20]);
const PROFILE: BlockProfile = BlockProfile {
    max_gas: 30_000_001,
    system_gas: 500_001,
    base_fee_floor: 7,
    elasticity: 2,
    change_denominator: 8,
};

fn hex_bytes(value: &serde_json::Value) -> Vec<u8> {
    alloy_primitives::hex::decode(value.as_str().unwrap()).unwrap()
}

fn slot(name: &str) -> U256 {
    U256::from_be_bytes(keccak256(format!("unicity.seal-registry.v1/{name}")).0)
}

/// What one application of one subset's vector produced.
#[derive(Debug, PartialEq, Eq)]
struct Outcome {
    block_hash: B256,
    state_root: B256,
    extra_data: Vec<u8>,
    execution_result: String,
    registry: BTreeMap<U256, U256>,
    post_state_root: B256,
}

fn apply(
    root_input: &[u8],
    transitions: Vec<Vec<u8>>,
    witnesses: Vec<Vec<u8>>,
    genesis_hash: B256,
) -> Outcome {
    // Builder wire shape and follower wire shape decode through the one codec and must agree.
    let build = SealBuildInput {
        root_input: root_input.to_vec().into(),
        transitions: transitions.iter().cloned().map(Into::into).collect(),
        pair_binding: Default::default(),
    };
    let companion = SealCompanion {
        root_input: root_input.to_vec().into(),
        pair_binding: Default::default(),
        witnesses: witnesses.into_iter().map(Into::into).collect(),
        provenance: "newPayload".into(),
    };
    let root: RootInputV2 = build.decode_root_input().expect("bft-core's build input decodes");
    assert_eq!(root, companion.decode_root_input().expect("bft-core's companion decodes"));
    assert_eq!(
        root.canonical_cbor().unwrap(),
        root_input,
        "the Go bytes are this kernel's canonical encoding"
    );
    assert_eq!(root.transitions.len(), 1, "a nonempty assignment transition");

    let genesis: Genesis = serde_json::from_str(GENESIS).unwrap();
    let chain_spec = Arc::new(ChainSpec::from_genesis(genesis));
    let parent = SealedHeader::new(chain_spec.genesis_header().clone(), genesis_hash);
    assert_eq!(parent.hash_slow(), genesis_hash, "the Go genesis hashes to the same block 0 here");
    let mut provider = FixtureProvider::from_json(GENESIS);
    provider.set_block_hash(0, genesis_hash);

    let root = Arc::new(root);
    let bound = Arc::new(
        BoundExecutionInput::from_validated_genesis(
            root.clone(),
            PROFILE,
            &parent,
            genesis_hash,
            FEE_COLLECTOR,
        )
        .expect("the acknowledgement binds to the genesis parent"),
    );
    let config = UnicityEvmConfig::new(EthEvmConfig::new(chain_spec), bound);
    let attrs = NextBlockEnvAttributes {
        timestamp: derive_timestamp(root.origin.reference_time, parent.timestamp).unwrap(),
        suggested_fee_recipient: FEE_COLLECTOR,
        prev_randao: derive_prev_randao(root.origin.root_round, root.authorized_round),
        gas_limit: PROFILE.max_gas,
        parent_beacon_block_root: Some(derive_beacon_root(
            root.origin.root_round,
            root.authorized_round,
        )),
        withdrawals: Some(Default::default()),
        extra_data: root.input_commitment().unwrap().to_vec().into(),
        slot_number: None,
    };
    let mut state = State::builder().with_database(provider.clone()).with_bundle_update().build();
    let built = build_complete(&config, &parent, attrs, &mut state, provider.clone(), vec![])
        .expect("builder path applies the acknowledgement");
    let replay = replay_complete(&config, provider.clone(), &provider, &built.outcome.block)
        .expect("replay path applies the same block");
    assert_eq!(replay.output.result, built.outcome.execution_result, "builder and replay agree");

    let header = built.outcome.block.clone().into_sealed_block().into_sealed_header();
    let mut post = provider.clone();
    post.apply_bundle(&state.bundle_state);
    assert_eq!(
        post.root(),
        header.state_root,
        "the header's state root is the applied state's root"
    );
    Outcome {
        block_hash: header.hash(),
        state_root: header.state_root,
        extra_data: header.extra_data.to_vec(),
        execution_result: format!("{:?}", built.outcome.execution_result),
        registry: post.storage_of(SEAL_REGISTRY),
        post_state_root: post.root(),
    }
}

#[test]
fn distinct_signer_subsets_of_a_nonempty_assignment_transition_reach_identical_state() {
    let vector: serde_json::Value = serde_json::from_str(VECTOR).unwrap();
    let root_input = hex_bytes(&vector["root_input"]);
    let transition = hex_bytes(&vector["transition"]);
    let commitment = hex_bytes(&vector["commitment"]);
    let beacon_root = hex_bytes(&vector["parent_beacon_block_root"]);
    let genesis_hash: B256 = {
        let parent = hex_bytes(&vector["parent_hash"]);
        B256::from_slice(&parent)
    };

    let subsets = vector["subsets"].as_array().unwrap();
    assert!(subsets.len() >= 2);
    let witnesses: Vec<Vec<Vec<u8>>> = subsets
        .iter()
        .map(|s| s["witnesses"].as_array().unwrap().iter().map(hex_bytes).collect())
        .collect();
    assert_ne!(
        witnesses[0], witnesses[1],
        "the vector's subsets really differ, in the witnesses only"
    );

    // Cross-implementation: this kernel derives the same commitment and beacon root bft-core's
    // paths handed it.
    let decoded = SealBuildInput {
        root_input: root_input.clone().into(),
        transitions: vec![transition.clone().into()],
        pair_binding: Default::default(),
    }
    .decode_root_input()
    .unwrap();
    assert_eq!(decoded.input_commitment().unwrap().as_slice(), commitment.as_slice());
    assert_eq!(
        derive_beacon_root(decoded.origin.root_round, decoded.authorized_round).as_slice(),
        beacon_root.as_slice()
    );
    assert_eq!((decoded.certified_epoch, decoded.authorized_epoch), (0, 1));
    assert_eq!(decoded.origin.root_epoch, vector["new_root_epoch"].as_u64().unwrap());

    let outcomes: Vec<Outcome> = witnesses
        .into_iter()
        .map(|w| apply(&root_input, vec![transition.clone()], w, genesis_hash))
        .collect();
    for other in &outcomes[1..] {
        assert_eq!(
            &outcomes[0], other,
            "every subset yields identical block, state root and registry state"
        );
    }
    assert_eq!(outcomes[0].extra_data, commitment, "the header commits to the Go commitment");

    // The registry is acknowledged: root epoch 2, shard epoch 1, one transition consumed.
    let registry = &outcomes[0].registry;
    assert_eq!(registry[&slot("assignment.rootEpoch")], U256::from(2));
    assert_eq!(registry[&slot("assignment.epoch")], U256::from(1));
    assert_eq!(registry[&slot("transition.cursor")], U256::from(1));
    assert_eq!(
        registry[&slot("round.authorized")],
        U256::from(vector["authorized_round"].as_u64().unwrap())
    );
}
