//! Replay every B2 call in the sealed corpus at the exact Go Kernel boundary.
use super::*;
use crate::tests::request;
use alloy_primitives::hex;
use serde_json::Value;
use std::{collections::BTreeMap, fs, path::PathBuf};

fn protocol() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("protocol")
}
fn json(name: &str) -> Value {
    serde_json::from_slice(&fs::read(protocol().join(name)).unwrap()).unwrap()
}
fn raw(v: &Value) -> Vec<u8> {
    hex::decode(v.as_str().unwrap()).unwrap()
}

#[test]
fn sealed_corpus_integrity() {
    let pin = json("pin.json");
    assert_eq!(pin["revision"], PROTOCOL_REVISION);
    let manifest = fs::read(protocol().join("vectors/SHA256SUMS")).unwrap();
    assert_eq!(hex::encode(hash(&manifest)), pin["corpusManifestSha256"]);
    assert_eq!(
        fs::read_to_string(protocol().join("vectors/MANIFEST.sha256")).unwrap().trim(),
        pin["corpusManifestSha256"].as_str().unwrap()
    );
    for line in std::str::from_utf8(&manifest).unwrap().lines() {
        let (digest, name) = line.split_once("  ").unwrap();
        assert_eq!(
            hex::encode(hash(&fs::read(protocol().join("vectors").join(name)).unwrap())),
            digest,
            "{name}"
        );
    }
    for (name, expected) in pin["sha256"].as_object().unwrap() {
        assert_eq!(
            hex::encode(hash(&fs::read(protocol().join(name)).unwrap())),
            expected.as_str().unwrap(),
            "{name}"
        );
    }
    assert_eq!(json("vectors/provenance.json")["generator"]["commit"], pin["oracleRevision"]);
}

#[test]
fn sealed_corpus_exact_kernel_outcomes() {
    let fixtures = json("vectors/config/fixtures.json");
    // Generated by executing the pinned Go Kernel after Replay verifies all 336
    // original cases. This preserves API-layer differences (zero prepare amount)
    // without guessing the expected ABI behavior from a direct relation error.
    let expectations = json("kernel-expectations.json");
    let mut expected: BTreeMap<_, _> = expectations
        .as_array()
        .unwrap()
        .iter()
        .map(|c| (c["id"].as_str().unwrap(), &c["expected"]))
        .collect();
    assert_eq!(expected.len(), 116);
    let mut total = 0;
    let mut replayed = 0;
    let mut failures = Vec::new();
    for family in
        ["config", "history", "lock", "policy", "proof", "return", "unlock", "vault", "wire"]
    {
        let cases = json(&format!("vectors/{family}/cases.json"));
        for c in cases["cases"].as_array().unwrap() {
            total += 1;
            let op = c["op"].as_str().unwrap();
            let input = match op {
                "kernel" => raw(&c["input"]),
                "prepareLock" | "mint" | "return" => {
                    let cfg = raw(&fixtures["fixtures"][c["cfg"].as_str().unwrap()]["cfg"]);
                    let payload = raw(&c["input"]);
                    let (operation, payload) = if op == "prepareLock" {
                        let n = c["aux"]["n"].as_str().unwrap().parse::<u64>().unwrap();
                        let amount = alloy_primitives::U256::from_str_radix(
                            c["aux"]["amount"].as_str().unwrap(),
                            10,
                        )
                        .unwrap();
                        let amount = amount.to_be_bytes::<32>();
                        let first = amount.iter().position(|b| *b != 0).unwrap_or(32);
                        (
                            0,
                            cbor::array(&[
                                &cbor::uint(n),
                                &cbor::bytes(&amount[first..]),
                                &payload,
                            ]),
                        )
                    } else {
                        (if op == "mint" { 1 } else { 2 }, payload)
                    };
                    request(operation, &cfg, &payload)
                }
                // These ops belong to SDK codecs, policy, offline backing,
                // composition or the vault; replay_oracle.go checks all of them.
                "trust-input" | "cfg-decode" | "identifiers" | "value-data" | "derive" | "unlock" |
                "policy-decode" | "envelope-policy" | "token-project" | "justification" |
                "lock-backing" | "mpt" | "compose" => continue,
                other => panic!("unclassified corpus operation {other}"),
            };
            replayed += 1;
            let id = c["id"].as_str().unwrap();
            let want = expected.remove(id).unwrap();
            match (run(&input, u64::MAX), want["status"].as_str().unwrap()) {
                (Ok(out), "ok") if out.bytes == raw(&want["output"]) => {}
                (Err(e), "error") if format!("Err{e:?}") == want["reason"].as_str().unwrap() => {}
                (got, _) => failures.push(format!("{id}: got {got:?}, want {want}")),
            }
        }
    }
    assert_eq!((total, replayed), (336, 116));
    assert!(expected.is_empty(), "unreplayed Kernel expectations");
    assert!(failures.is_empty(), "{}", failures.join("\n"));
}
