#!/usr/bin/env python3
"""Independent generator for pair-binding-vectors.json.

Writes its own minimal RFC 8949 deterministic CBOR encoder and shares no code with the Rust
encoder. The root input bytes come from v2-vectors.json, which bft-core's Go encoder produced, so
`rootInputHash` is the SHA-256 of Go bytes. The Go side adopts the same file as its vector.
"""
import hashlib
import json
import pathlib

HERE = pathlib.Path(__file__).parent


def head(major, n):
    if n < 24:
        return bytes([major << 5 | n])
    for width, info in ((1, 24), (2, 25), (4, 26), (8, 27)):
        if n < 1 << (8 * width):
            return bytes([major << 5 | info]) + n.to_bytes(width, "big")
    raise ValueError(n)


def uint(n):
    return head(0, n)


def bstr(b):
    return head(2, len(b)) + b


def tstr(s):
    b = s.encode()
    return head(3, len(b)) + b


def arr(items):
    return head(4, len(items)) + b"".join(items)


def sha(b):
    return hashlib.sha256(b).digest()


def h(b):
    return "0x" + b.hex()


def word(byte):
    return bytes([byte]) * 32


DOMAIN, VERSION = "UNICITY_PAIR_BINDING", 1
src = json.loads((HERE / "v2-vectors.json").read_text())
vector = next(v for v in src["vectors"] if v["name"] == "ordinary_successful")
root_cbor = bytes.fromhex(vector["rootInput"]["cbor"][2:])
origin = vector["source"]
transition = bytes.fromhex("a1b2c3")  # opaque: the hash covers bytes, not meaning


def transitions_hash(ts):
    return sha(arr([bstr(t) for t in ts]))


def attributes_digest(ts, randao, recipient, beacon):
    return sha(arr([tstr("UNICITY_PAIR_JOB"), uint(1), uint(ts), bstr(randao), bstr(recipient), bstr(beacon)]))


def binding(fields, kind, subject):
    return arr([
        tstr(DOMAIN), uint(VERSION),
        uint(fields["networkId"]), bstr(fields["rootGenesisId"]), bstr(fields["executionGenesisHash"]),
        bstr(fields["parentHash"]), uint(fields["parentNumber"]),
        uint(fields["originRootEpoch"]), uint(fields["originRootRound"]),
        bstr(fields["configurationId"]), bstr(fields["activationId"]),
        bstr(fields["rootInputHash"]), bstr(fields["transitionsHash"]),
        uint(kind), bstr(subject),
    ])


fields = {
    "networkId": origin["networkId"],
    "rootGenesisId": word(0x51),
    "executionGenesisHash": word(0x52),
    "parentHash": word(0x53),
    "parentNumber": 7,
    "originRootEpoch": origin["rootEpoch"],
    "originRootRound": origin["rootRound"],
    "configurationId": bytes.fromhex(origin["shardConfHash"][2:]),
    "activationId": word(0x55),
    "rootInputHash": sha(root_cbor),
    "transitionsHash": transitions_hash([]),
}
digest = attributes_digest(1681971100, word(0x61), bytes([0x77] * 20), word(0x62))
block_hash = word(0x63)
build = binding(fields, 1, digest)
imp = binding(fields, 2, block_hash)


def enc(f):
    return {k: (h(v) if isinstance(v, bytes) else v) for k, v in f.items()}


invalid = {
    "empty": b"",
    "trailing_byte": imp + b"\x00",
    "truncated": imp[:-1],
    "indefinite_array": b"\x9f" + imp[1:] + b"\xff",
    "non_minimal_version": imp[: 2 + len(DOMAIN)] + b"\x18\x01" + imp[2 + len(DOMAIN) + 1:],
    "wrong_domain": imp[:2] + b"X" + imp[3:],
    "wrong_version": imp[: 2 + len(DOMAIN)] + b"\x02" + imp[2 + len(DOMAIN) + 1:],
    "arity_fourteen": b"\x8e" + imp[1:],
    "unknown_subject_kind": binding(fields, 3, block_hash),
    "zero_parent": binding({**fields, "parentHash": bytes(32)}, 2, block_hash),
    "short_word": binding({**fields, "configurationId": bytes(31)}, 2, block_hash),
}

out = {
    "format": "unicity-pair-binding-vectors",
    "version": 1,
    "note": "Generated by generate-pair-binding-vectors.py with an independent encoder; "
            "rootInput is the Go-produced ordinary_successful vector of v2-vectors.json.",
    "rootInput": h(root_cbor),
    "transition": h(transition),
    "fields": enc(fields),
    "emptyTransitionsHash": h(transitions_hash([])),
    "oneTransitionHash": h(transitions_hash([transition])),
    "attributes": {
        "timestamp": 1681971100,
        "prevRandao": h(word(0x61)),
        "suggestedFeeRecipient": h(bytes([0x77] * 20)),
        "parentBeaconBlockRoot": h(word(0x62)),
        "digest": h(digest),
    },
    "blockHash": h(block_hash),
    "build": h(build),
    "import": h(imp),
    "invalid": {k: h(v) for k, v in invalid.items()},
}
(HERE / "pair-binding-vectors.json").write_text(json.dumps(out, indent=2) + "\n")
